export const START_GETTING_AUTH_STATE = "START_GETTING_AUTH_STATE";
export const SAVE_GETTING_AUTH_STATE = "SAVE_GETTING_AUTH_STATE";
export const ERROR_GETTING_AUTH_STATE = "ERROR_GETTING_AUTH_STATE";
