export const START_GETTING_COMPANY_BY_ID = "START_GETTING_COMPANY_BY_ID"
export const SAVE_GETTING_COMPANY_BY_ID = "SAVE_GETTING_COMPANY_BY_ID"
export const ERROR_GETTING_COMPANY_BY_ID = "ERROR_GETTING_COMPANY_BY_ID"