export const START_GETTING_ALL_INDUSTRIES = "START_GETTING_ALL_INDUSTRIES"
export const SAVE_GETTING_LIST_INDUSTRIES = "SAVE_GETTING_LIST_INDUSTRIES"
export const ERROR_GETTING_LIST_INDUSTRIES = "ERROR_GETTING_LIST_INDUSTRIES"