export const START_GETTING_ALL_COMPANIES = "START_GETTING_ALL_COMPANIES"
export const SAVE_GETTING_LIST_COMPANIES = "SAVE_GETTING_LIST_COMPANIES"
export const ERROR_GETTING_LIST_COMPANIES = "ERROR_GETTING_LIST_COMPANIES"