export const START_GETTING_USER_CARD_DATA = "START_GETTING_USER_CARD_DATA"
export const SAVE_USER_CARD_DATA = "SAVE_USER_CARD_DATA"
export const ERROR_GETTING_USER_CARD_DATA = "ERROR_GETTING_USER_CARD_DATA"