export const START_GETTING_PAYMENT_PERDAY = "START_GETTING_PAYMENT_PERDAY"
export const SAVE_GETTING_PAYMENT_PERDAY = "SAVE_GETTING_PAYMENT_PERDAY"
export const ERROR_GETTING_PAYMENT_PERDAY = "ERROR_GETTING_PAYMENT_PERDAY"